version: "3.9"

services:
  app_1:
    build: app_1
    ports:
      - "5000"
  app_2:
    build: app_2
    ports:
      - "5000"
  app_3:
    build: app_3
    ports:
      - "5000"
  nginx: 
    image: nginx:latest
    ports:
      - "80:80"
    volumes:  
      - ./nginx.conf:/etc/nginx/nginx.conf

