version: "3.9"

services:
  app_1:
    build: app_1
    ports:
      - "5000"
    restart: always
    volumes:
      - .:/code
      - log:/var/log
    deploy:
      replicas: 3
    depends_on:
      - db
      
  proxy:
    build: proxy

    ports:
      - "80:80"
    depends_on:
      - app_1
      - db
    restart: always
    volumes:  
      - log:/var/log/nginx
    deploy:
      replicas: 1

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - db-data:/var/lib/mysql
      - log:/var/log/mysql
    ports:
      - "3306:3306"

volumes:
  log:
  db-data:



  


